"""Create books table

Revision ID: 7f62f7ce256f
Revises: 
Create Date: 2025-09-09 19:41:02.635875

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = '7f62f7ce256f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
