"""Add database indexes for performance

Revision ID: b8fd17dcb42f
Revises: 7f62f7ce256f
Create Date: 2025-09-09 20:15:42.418209

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'b8fd17dcb42f'
down_revision: Union[str, None] = '7f62f7ce256f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_author_creator', 'books', ['author', 'created_by'], unique=False)
    op.create_index('idx_created_on_desc', 'books', ['created_on'], unique=False)
    op.create_index('idx_title_author', 'books', ['title', 'author'], unique=False)
    op.create_index(op.f('ix_books_author'), 'books', ['author'], unique=False)
    op.create_index(op.f('ix_books_created_by'), 'books', ['created_by'], unique=False)
    op.create_index(op.f('ix_books_created_on'), 'books', ['created_on'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_created_on'), table_name='books')
    op.drop_index(op.f('ix_books_created_by'), table_name='books')
    op.drop_index(op.f('ix_books_author'), table_name='books')
    op.drop_index('idx_title_author', table_name='books')
    op.drop_index('idx_created_on_desc', table_name='books')
    op.drop_index('idx_author_creator', table_name='books')
    # ### end Alembic commands ###
